package main

var symbols = map[string]map[string]string {
	"bash": {
		"simple_expansion": "TSNone",
		"expansion": "TSNone",
		"special_variable_name": "TSConstant",
		"comment": "TSComment",
		"test_operator": "TSString",
		"variable_name": "TSVariable",
		"regex": "TSStringRegex",
	},
	"c": {
		"identifier": "TSVariable",
		"string_literal": "TSString",
		"system_lib_string": "TSString",
		"escape_sequence": "TSStringEscape",
		"null": "TSConstBuiltin",
		"number_literal": "TSNumber",
		"char_literal": "TSCharacter",
		"statement_identifier": "TSLabel",
		"comment": "TSComment",
		"preproc_params": "TSParameter",
		"ERROR": "TSError",
	},
	"cpp": {
		"identifier": "TSVariable",
		"string_literal": "TSString",
		"system_lib_string": "TSString",
		"escape_sequence": "TSStringEscape",
		"null": "TSConstBuiltin",
		"number_literal": "TSNumber",
		"char_literal": "TSCharacter",
		"statement_identifier": "TSLabel",
		"comment": "TSComment",
		"preproc_params": "TSParameter",
		"ERROR": "TSError",
		"namespace_identifier": "TSNamespace",
		"operator_name": "TSFunction",
		"this": "TSVariableBuiltin",
		"nullptr": "TSConstant",
		"true": "TSBoolean",
		"false": "TSBoolean",
		"raw_string_literal": "TSString",
		"attribute": "TSAttribute",
	},
	"csharp": {
	},
	"css": {
		"comment": "TSComment",
		"function_name": "TSFunction",
		"ERROR": "TSError",
	},
	"dockerfile": {
		"comment": "TSComment",
		"double_quoted_string": "TSString",
	},
	"ecma": {
		"identifier": "TSVariable",
		"property_identifier": "TSProperty",
		"shorthand_property_identifier": "TSProperty",
		"this": "TSVariableBuiltin",
		"super": "TSVariableBuiltin",
		"true": "TSBoolean",
		"false": "TSBoolean",
		"null": "TSConstBuiltin",
		"comment": "TSComment",
		"string": "TSString",
		"regex": "TSPunctDelimiter",
		"regex_pattern": "TSStringRegex",
		"template_string": "TSString",
		"number": "TSNumber",
		"template_substitution": "TSNone",
	},
	"elm": {
	},
	"go": {
		"type_identifier": "TSType",
		"field_identifier": "TSProperty",
		"identifier": "TSVariable",
		"package_identifier": "TSVariable",
		"interpreted_string_literal": "TSString",
		"raw_string_literal": "TSString",
		"rune_literal": "TSString",
		"escape_sequence": "TSStringEscape",
		"int_literal": "TSNumber",
		"float_literal": "TSFloat",
		"imaginary_literal": "TSNumber",
		"true": "TSBoolean",
		"false": "TSBoolean",
		"nil": "TSConstBuiltin",
		"comment": "TSComment",
		"ERROR": "TSError",
	},
	"hcl": {
		"numeric_lit": "TSNumber",
		"bool_lit": "TSBoolean",
		"null_lit": "TSConstant",
		"comment": "TSComment",
		"identifier": "TSVariable",
		"ERROR": "TSError",
	},
	"html": {
		"tag_name": "TSTag",
		"erroneous_end_tag_name": "TSError",
		"comment": "TSComment",
		"attribute_name": "TSProperty",
		"attribute_value": "TSString",
		"quoted_attribute_value": "TSString",
		"text": "TSNone",
		"doctype": "TSConstant",
	},
	"html_tags": {
		"tag_name": "TSTag",
		"erroneous_end_tag_name": "TSError",
		"comment": "TSComment",
		"attribute_name": "TSProperty",
		"attribute_value": "TSString",
		"quoted_attribute_value": "TSString",
		"text": "TSNone",
	},
	"java": {
		"identifier": "TSVariable",
		"super": "TSFunctionBuiltin",
		"type_identifier": "TSType",
		"this": "TSVariableBuiltin",
		"character_literal": "TSCharacter",
		"string_literal": "TSString",
		"null_literal": "TSConstBuiltin",
		"comment": "TSComment",
	},
	"javascript": {
		"identifier": "TSVariable",
		"property_identifier": "TSProperty",
		"shorthand_property_identifier": "TSProperty",
		"this": "TSVariableBuiltin",
		"super": "TSVariableBuiltin",
		"true": "TSBoolean",
		"false": "TSBoolean",
		"null": "TSConstBuiltin",
		"comment": "TSComment",
		"string": "TSString",
		"regex": "TSPunctDelimiter",
		"regex_pattern": "TSStringRegex",
		"template_string": "TSString",
		"number": "TSNumber",
		"template_substitution": "TSNone",
		"jsx_text": "TSNone",
	},
	"jsx": {
		"jsx_text": "TSNone",
	},
	"lua": {
		"self": "TSVariableBuiltin",
		"identifier": "TSVariable",
		"nil": "TSConstBuiltin",
		"spread": "TSConstant",
		"property_identifier": "TSProperty",
		"method": "TSMethod",
		"comment": "TSComment",
		"string": "TSString",
		"number": "TSNumber",
		"label_statement": "TSLabel",
		"shebang": "TSComment",
		"ERROR": "TSError",
	},
	"ocaml": {
		"method_name": "TSMethod",
		"value_pattern": "TSParameter",
		"character": "TSCharacter",
		"string": "TSString",
		"quoted_string": "TSString",
		"escape_sequence": "TSStringEscape",
		"attribute_id": "TSProperty",
		"ERROR": "TSError",
	},
	"php": {
		"variable_name": "TSVariable",
		"named_type": "TSType",
		"relative_scope": "TSVariableBuiltin",
		"boolean": "TSBoolean",
		"null": "TSConstBuiltin",
		"integer": "TSNumber",
		"float": "TSFloat",
		"comment": "TSComment",
		"ERROR": "TSError",
	},
	"python": {
		"identifier": "TSVariable",
		"interpolation": "TSNone",
		"decorator": "TSFunction",
		"none": "TSConstBuiltin",
		"integer": "TSNumber",
		"float": "TSFloat",
		"comment": "TSComment",
		"string": "TSString",
		"escape_sequence": "TSStringEscape",
		"ERROR": "TSError",
	},
	"ruby": {
		"identifier": "TSVariable",
		"interpolation": "TSNone",
		"constant": "TSType",
		"regex": "TSStringRegex",
		"escape_sequence": "TSStringEscape",
		"integer": "TSNumber",
		"float": "TSFloat",
		"comment": "TSComment",
		"ERROR": "TSError",
	},
	"rust": {
		"identifier": "TSVariable",
		"type_identifier": "TSType",
		"primitive_type": "TSTypeBuiltin",
		"field_identifier": "TSField",
		"crate": "TSNamespace",
		"metavariable": "TSFunctionMacro",
		"self": "TSVariableBuiltin",
		"boolean_literal": "TSBoolean",
		"integer_literal": "TSNumber",
		"float_literal": "TSFloat",
		"escape_sequence": "TSStringEscape",
	},
	"svelte": {
		"tag_name": "TSTag",
		"erroneous_end_tag_name": "TSError",
		"comment": "TSComment",
		"attribute_name": "TSProperty",
		"attribute_value": "TSString",
		"quoted_attribute_value": "TSString",
		"text": "TSNone",
		"raw_text_expr": "TSNone",
	},
	"toml": {
		"bare_key": "TSTypeBuiltin",
		"string": "TSString",
		"boolean": "TSConstBuiltin",
		"integer": "TSNumber",
		"float": "TSFloat",
		"comment": "TSComment",
		"ERROR": "TSError",
	},
	"tsx": {
		"type_identifier": "TSType",
		"predefined_type": "TSTypeBuiltin",
		"undefined": "TSVariableBuiltin",
		"jsx_text": "TSNone",
	},
	"typescript": {
		"identifier": "TSVariable",
		"property_identifier": "TSProperty",
		"shorthand_property_identifier": "TSProperty",
		"this": "TSVariableBuiltin",
		"super": "TSVariableBuiltin",
		"true": "TSBoolean",
		"false": "TSBoolean",
		"null": "TSConstBuiltin",
		"comment": "TSComment",
		"string": "TSString",
		"regex": "TSPunctDelimiter",
		"regex_pattern": "TSStringRegex",
		"template_string": "TSString",
		"number": "TSNumber",
		"template_substitution": "TSNone",
		"type_identifier": "TSType",
		"predefined_type": "TSTypeBuiltin",
		"undefined": "TSVariableBuiltin",
	},
	"yaml": {
		"boolean_scalar": "TSBoolean",
		"null_scalar": "TSConstBuiltin",
		"double_quote_scalar": "TSString",
		"single_quote_scalar": "TSString",
		"escape_sequence": "TSStringEscape",
		"integer_scalar": "TSNumber",
		"float_scalar": "TSNumber",
		"comment": "TSComment",
		"anchor_name": "TSType",
		"alias_name": "TSType",
		"tag": "TSType",
		"yaml_directive": "TSKeyword",
		"ERROR": "TSError",
	},
}
var keywords = map[string]map[string]string {
	"bash": {
		"function": "TSKeywordFunction",
	},
	"c": {
		"return": "TSKeywordReturn",
		"#define": "TSConstMacro",
		"#include": "TSInclude",
		"...": "TSPunctSpecial",
	},
	"cpp": {
		"return": "TSKeywordReturn",
		"#define": "TSConstMacro",
		"#include": "TSInclude",
		"...": "TSPunctSpecial",
		"::": "TSOperator",
	},
	"csharp": {
	},
	"css": {
	},
	"dockerfile": {
	},
	"ecma": {
		"...": "TSPunctSpecial",
		";": "TSPunctDelimiter",
		".": "TSPunctDelimiter",
		",": "TSPunctDelimiter",
		"?.": "TSPunctDelimiter",
		"(": "TSPunctBracket",
		")": "TSPunctBracket",
		"[": "TSPunctBracket",
		"]": "TSPunctBracket",
		"{": "TSPunctBracket",
		"}": "TSPunctBracket",
	},
	"elm": {
	},
	"go": {
		"func": "TSKeywordFunction",
		"return": "TSKeywordReturn",
		"for": "TSRepeat",
		".": "TSPunctDelimiter",
		",": "TSPunctDelimiter",
		":": "TSPunctDelimiter",
		";": "TSPunctDelimiter",
		"(": "TSPunctBracket",
		")": "TSPunctBracket",
		"{": "TSPunctBracket",
		"}": "TSPunctBracket",
		"[": "TSPunctBracket",
		"]": "TSPunctBracket",
	},
	"hcl": {
	},
	"html": {
		"=": "TSOperator",
		"<!": "TSTagDelimiter",
	},
	"html_tags": {
		"=": "TSOperator",
	},
	"java": {
		"import": "TSInclude",
		"package": "TSInclude",
	},
	"javascript": {
		"...": "TSPunctSpecial",
		";": "TSPunctDelimiter",
		".": "TSPunctDelimiter",
		",": "TSPunctDelimiter",
		"?.": "TSPunctDelimiter",
		"(": "TSPunctBracket",
		")": "TSPunctBracket",
		"[": "TSPunctBracket",
		"]": "TSPunctBracket",
		"{": "TSPunctBracket",
		"}": "TSPunctBracket",
	},
	"jsx": {
	},
	"lua": {
		"return": "TSKeywordReturn",
	},
	"ocaml": {
		"%": "TSPunctSpecial",
	},
	"php": {
		"return": "TSKeywordReturn",
	},
	"python": {
	},
	"ruby": {
		"defined?": "TSFunction",
	},
	"rust": {
		"$": "TSFunctionMacro",
		"return": "TSKeywordReturn",
		"fn": "TSKeywordFunction",
	},
	"svelte": {
		"=": "TSOperator",
	},
	"toml": {
	},
	"tsx": {
	},
	"typescript": {
		"...": "TSPunctSpecial",
		";": "TSPunctDelimiter",
		".": "TSPunctDelimiter",
		",": "TSPunctDelimiter",
		"?.": "TSPunctDelimiter",
		"(": "TSPunctBracket",
		")": "TSPunctBracket",
		"[": "TSPunctBracket",
		"]": "TSPunctBracket",
		"{": "TSPunctBracket",
		"}": "TSPunctBracket",
	},
	"yaml": {
	},
}
